### ISSUE TITLE
ch9102x driver for m16p?

### ISSUE THREAD

**Issue by drbeat** [throwaway96/webos-kernel-drivers#2]
Hi,
as I tried ch341.ko which doesnt want to detect my esp32
Is it possible to build ch343.ko for ch9102x? https://github.com/WCHSoftGroup/ch343ser_linux

thanks in advance

**Comment by throwaway96** [comment]
@drbeat

I can try when I have some free time, but you didn't say what your SoC and webOS version were. Also, if it's not one that I've previously built drivers for, please provide a copy of `/proc/config.gz`.

However, I've already built that module for O18 (2019); it should still be available somewhere on the [OpenLGTV Discord](https://discord.gg/xWqRVEm).

To use it, you will probably have to manually unbind `cdc_acm` and bind `usb_ch343` to the device.

**Comment by drbeat** [comment]
Sorry I forgot to add my SoC.
Linux LGwebOSTV 4.4.3-119.drd4tv.5 #1 SMP PREEMPT Wed Aug 18 01:16:58 EDT 2021 armv7l GNU/Linux
which is the m16p SoC

I found the ch343.ko for O18 on the discord. Is it safe to use it for a different kernel Version eventhough its just a patch level difference?

**Comment by throwaway96** [comment]
> Is it safe to use it for a different kernel Version eventhough its just a patch level difference?

You can try it. The worst that's likely to happen is a kernel panic. Just don't load it in an init script before you've tested it.

**Comment by drbeat** [comment]
Did not work.
Nvm I ordered a Wemos D1 now.
